name: Mirror Repo

on:
  push:
    branches: [ main ] # adapte si c'est dev ou master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to second repo
        run: |
          git remote add mirror https://${{ secrets.TOKEN }}@github.com/mafiaotters/otter-management.git
          git push --mirror mirror
