name: Mirror Repo

on:
  push:
    branches: [ main ] # adapte si ta branche principale s'appelle master ou dev

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug token (vérifie que le secret est lu)
        run: |
          if [ -z "$TOKEN" ]; then
            echo "❌ Le token est VIDE, vérifie ton secret !"
            exit 1
          else
            echo "✅ Token détecté, longueur : ${#TOKEN} caractères"
          fi
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Push to second repo
        run: |
          git remote add mirror https://${{ secrets.TOKEN }}@github.com/mafiaotters/otter-management.git
          git push --mirror mirror
