name: Mirror Repo

on:
  push:
    branches: [ main ] # ou master si c'est la branche principale

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to second repo
        run: |
          git remote add mirror https://<TOKEN>@github.com/MonComptePerso/otter-management.git
          git push --mirror mirror
