name: Mirror Repo

on:
  push:
    branches: [ main ] # adapte si ta branche principale est "dev" ou "master"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test access to second repo
        run: |
          echo "🔍 Test de connexion au repo cible..."
          git ls-remote https://${{ secrets.TOKEN }}@github.com/mafiaotters/otter-management.git
        continue-on-error: false

      - name: Push to second repo
        run: |
          git remote add mirror https://${{ secrets.TOKEN }}@github.com/mafiaotters/otter-management.git
          git push --mirror mirror
